ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCYYNEH0YxvrmDEFybOgEr8I9ztkGYJ/+AxwB1AZvT/Ko7p3uztHqjCpkD50XX7rCI43oQMy6V8lrinBlw/tvZ8gQxD+FCsscUQwM2q8ymChFoKmHZfCYU6594zNe3CyBY//EwdTIi0hI0Je+zAgxzKqIApbPXMKw2mOqE6BYHexPPhVVbaYkDPjKkkpnVGTLJfhFv+m10eTrKUaNF8jV6lp5O750XWlmXz7ef9+5uxgQck4P2IYmcMGD/Z8jReoxlV1zz1qv8PDI3NGnsiDCHrbXXbticzJIdyjeCZ8IcJj1iLt/Bk5Nn+5pDocfhs7ewqLOiqkbl6GV4IjaYA45HbJtFZg4ArCFGB+FW4Al17Gc4559rc1LoeIvgQk+db3q4ZCgO1mGb04/5JYOAm5PwT+q7m3+zgOCqJKjpA2MrAn2BH3lczUaOHgPnb2X0RbDDFak6bF4Fz8G5HaPmRqIr0bZORA9DqY7VBPpc84Jzh1+r1C6j+emJcY3r6dNuB1bU= root@hatchet


ARG CONFIGURE_OPTS="--enable-seccomp"

RUN pacman -Sy && pacman --noconfirm -S gcc automake autoconf libevent libseccomp git make perl pkgconf
RUN ln -s /usr/bin/core_perl/prove /usr/bin/prove

RUN useradd -ms /bin/bash memcached
ADD . /src
WORKDIR /src

RUN aclocal
RUN autoheader
RUN automake --gnu --add-missing
RUN autoconf

RUN ./configure ${CONFIGURE_OPTS}
RUN make -j

USER memcached

CMD make test
